-- ternarios de tipo: condicion?exp1:exp2
-- exp1, exp2 pueden ser ternarios o variables
-- las variables pueden ser a, b, c, d
-- las condiciones son booleanas y son: variable, operador, variable
-- los operadores son: <, >, <=, >=, ==, !=
